//@error-in-other-file: Unsat
//@compile-flags: -C debug-assertions=off
//@rustc-env: THRUST_SOLVER=tests/thrust-pcsat-wrapper

// An impl that only carries `#[automatically_derived]` was not generated by a built-in derive, so
// its body is checked against std.rs's `PartialEq::eq` contract.

struct W(i64);

impl thrust_models::Model for W {
    type Ty = W;
}

#[automatically_derived]
impl PartialEq for W {
    fn eq(&self, other: &W) -> bool {
        self.0 <= other.0
    }
}

fn main() {
    assert!(W(1) != W(2));
}
