//@error-in-other-file: Unsat
//@compile-flags: -C debug-assertions=off
//@rustc-env: THRUST_SOLVER=tests/thrust-pcsat-wrapper THRUST_SOLVER_TIMEOUT_SECS=300 COAR_IMAGE=coar:develop-2493045c3

// Scalability family, variant per_instance, the instantiation at S9 alone. P_k in this
// variant is the programs t0 .. t(k-1). Generated by generate.py of the scalability
// evaluation; do not edit by hand.

#[thrust_macros::context]
trait Step {
    #[thrust_macros::requires(Self::inv(x))]
    #[thrust_macros::ensures(Self::inv(result) && result > x)]
    fn step(&self, x: i64) -> i64;

    #[thrust_macros::predicate]
    fn inv(x: i64) -> bool;
}

#[derive(PartialEq)]
struct S9 {}

impl thrust_models::Model for S9 {
    type Ty = S9;
}

#[thrust_macros::context]
impl Step for S9 {
    fn step(&self, x: i64) -> i64 {
        x + 1
    }

    #[thrust_macros::predicate]
    fn inv(x: i64) -> bool {
        x >= 9
    }
}

#[thrust_macros::requires(S9::inv(x) && n >= 0)]
#[thrust_macros::ensures(S9::inv(result) && result >= x + n)]
fn repeat_s9(a: &S9, x: i64, n: i64) -> i64 {
    let mut v = x;
    let mut i = 0;
    while i < n {
        v = a.step(v);
        i += 1;
    }
    v
}

fn main() {
    let r9 = repeat_s9(&S9 {}, 8, 3);
    assert!(r9 >= 12);
}
