//@error-in-other-file: Unsat
//@compile-flags: -C debug-assertions=off
//@rustc-env: THRUST_SOLVER=tests/thrust-pcsat-wrapper THRUST_SOLVER_TIMEOUT_SECS=300 COAR_IMAGE=coar:develop-2493045c3

// Scalability family, variant per_instance, the instantiation at S11 alone. P_k in this
// variant is the programs t0 .. t(k-1). Generated by generate.py of the scalability
// evaluation; do not edit by hand.

#[thrust_macros::context]
trait Step {
    #[thrust_macros::requires(Self::inv(x))]
    #[thrust_macros::ensures(Self::inv(result) && result > x)]
    fn step(&self, x: i64) -> i64;

    #[thrust_macros::predicate]
    fn inv(x: i64) -> bool;
}

#[derive(PartialEq)]
struct S11 {}

impl thrust_models::Model for S11 {
    type Ty = S11;
}

#[thrust_macros::context]
impl Step for S11 {
    fn step(&self, x: i64) -> i64 {
        x + 3
    }

    #[thrust_macros::predicate]
    fn inv(x: i64) -> bool {
        x >= 11
    }
}

#[thrust_macros::requires(S11::inv(x) && n >= 0)]
#[thrust_macros::ensures(S11::inv(result) && result >= x + n)]
fn repeat_s11(a: &S11, x: i64, n: i64) -> i64 {
    let mut v = x;
    let mut i = 0;
    while i < n {
        v = a.step(v);
        i += 1;
    }
    v
}

fn main() {
    let r11 = repeat_s11(&S11 {}, 10, 3);
    assert!(r11 >= 14);
}
